import { useEffect, useState } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import Layout from '../components/layout/Layout'
import { getSchema, getInsights } from '../api'

export default function Export() {
  const { fileId } = useParams()
  const navigate   = useNavigate()

  const [schema,   setSchema]   = useState(null)
  const [insights, setInsights] = useState([])
  const [selected, setSelected] = useState([])
  const [format,   setFormat]   = useState('pdf')
  const [loading,  setLoading]  = useState(true)
  const [exporting,setExporting]= useState(false)

  useEffect(() => {
  const load = async () => {
    try {
      const schemaRes = await getSchema(fileId)
      setSchema(schemaRes.data)

      // Try to get insights from session cache first (has result data)
      const cacheKey = `workspace_${fileId}`
      const cached   = sessionStorage.getItem(cacheKey)

      if (cached) {
        const parsed = JSON.parse(cached)
        if (parsed.insights && parsed.insights.length > 0) {
          setInsights(parsed.insights)
          setSelected(parsed.insights.map(i => i.id || i.title))
          setLoading(false)
          return
        }
      }

      // Fallback to API
      const insightRes = await getInsights(fileId)
      setInsights(insightRes.data)
      setSelected(insightRes.data.map(i => i.id))

    } catch (err) {
      console.error(err)
    } finally {
      setLoading(false)
    }
  }
  load()
}, [fileId])




 const toggleSelect = (id) => {
  setSelected(prev =>
    prev.includes(id)
      ? prev.filter(x => x !== id)
      : [...prev, id]
  )
}

const selectAll = () => setSelected(insights.map(i => i.id || i.title))
const clearAll  = () => setSelected([])





  const handleExportPDF = async () => {
    setExporting(true)
    try {
      // Build a printable HTML page with selected insights


const selectedInsights = insights.filter(i => selected.includes(i.id || i.title))


      const html = `
        <!DOCTYPE html>
        <html>
        <head>
          <title>${schema?.filename} — DataLens Report</title>
          <style>
            body { font-family: system-ui, sans-serif; color: #1A1A2E; padding: 2rem; }
            h1 { font-size: 22px; font-weight: 700; margin-bottom: 4px; }
            .meta { font-size: 13px; color: #6B8BAA; margin-bottom: 2rem; }
            .insight { border: 1px solid #E2EEF9; border-radius: 10px; padding: 1rem; margin-bottom: 1rem; break-inside: avoid; }
            .insight-title { font-size: 14px; font-weight: 600; margin-bottom: 10px; }
            table { width: 100%; border-collapse: collapse; font-size: 12px; margin-top: 8px; }
            th { background: #F7FBFF; padding: 6px 10px; text-align: left; border-bottom: 1px solid #E2EEF9; color: #6B8BAA; }
            td { padding: 6px 10px; border-bottom: 1px solid #E2EEF9; }
            .footer { margin-top: 2rem; font-size: 11px; color: #A0B4C8; text-align: center; }
          </style>
        </head>
        <body>
          <h1>${schema?.filename}</h1>
          <div class="meta">
            ${schema?.row_count?.toLocaleString()} rows · ${schema?.col_count} columns · 
            Generated by DataLens on ${new Date().toLocaleDateString()}
          </div>
          ${selectedInsights.map(insight => {
            const result = insight.result || {}
            const rows   = result.rows   || []
            const cols   = result.columns|| []
            return `
              <div class="insight">
                <div class="insight-title">${insight.title}</div>
                ${cols.length > 0 ? `
                  <table>
                    <thead><tr>${cols.slice(0,4).map(c => `<th>${c}</th>`).join('')}</tr></thead>
                    <tbody>
                      ${rows.slice(0,8).map(row =>
                        `<tr>${cols.slice(0,4).map(c => `<td>${row[c] !== null ? (typeof row[c] === 'number' && row[c] % 1 !== 0 ? row[c].toFixed(2) : row[c]) : '-'}</td>`).join('')}</tr>`
                      ).join('')}
                    </tbody>
                  </table>
                ` : '<p style="color:#6B8BAA;font-size:13px">No data available</p>'}
              </div>
            `
          }).join('')}
          <div class="footer">
            ⚠️ DataLens can make mistakes. Please verify important results before making decisions.
          </div>
        </body>
        </html>
      `

      // Open print dialog
      const win = window.open('', '_blank')
      win.document.write(html)
      win.document.close()
      win.focus()
      setTimeout(() => {
        win.print()
        win.close()
      }, 500)

    } catch (err) {
      alert('Export failed — please try again')
    } finally {
      setExporting(false)
    }
  }

  const handleExportCSV = () => {
    const selectedInsights = insights.filter(i => selected.includes(i.id))
    let csv = ''

    selectedInsights.forEach(insight => {
      const rows = insight.result?.rows   || []
      const cols = insight.result?.columns|| []
      if (cols.length === 0) return

      csv += `# ${insight.title}\n`
      csv += cols.join(',') + '\n'
      rows.forEach(row => {
        csv += cols.map(c => {
          const val = row[c]
          if (val === null || val === undefined) return ''
          if (typeof val === 'string' && val.includes(',')) return `"${val}"`
          return val
        }).join(',') + '\n'
      })
      csv += '\n'
    })

    const blob = new Blob([csv], { type:'text/csv' })
    const url  = URL.createObjectURL(blob)
    const a    = document.createElement('a')
    a.href     = url
    a.download = `${schema?.filename?.replace('.csv','')}_report.csv`
    a.click()
    URL.revokeObjectURL(url)
  }

const handleShare = () => {
  const shareUrl = `${window.location.origin}/report/${fileId}`
  navigator.clipboard.writeText(shareUrl)
  alert(`Share link copied to clipboard!\n\n${shareUrl}`)
}



  if (loading) return (
    <Layout>
      <div style={{ textAlign:'center', padding:'4rem' }}>
        <p style={{ fontSize:'18px', color:'#1A1A2E' }}>Loading...</p>
      </div>
    </Layout>
  )

  return (
    <Layout>
      <div style={{ display:'flex', justifyContent:'space-between', alignItems:'flex-start', marginBottom:'1.5rem', flexWrap:'wrap', gap:'10px' }}>
        <div>
          <button
            onClick={() => navigate(`/workspace/${fileId}`)}
            style={{ background:'transparent', border:'none', color:'#6B8BAA', fontSize:'14px', cursor:'pointer', padding:'0 0 6px', display:'block' }}
          >
            &larr; Back to workspace
          </button>
          <h1 style={{ fontSize:'22px', fontWeight:'700', color:'#1A1A2E' }}>
            Export report
          </h1>
          <p style={{ fontSize:'13px', color:'#6B8BAA', marginTop:'4px' }}>
            {schema?.filename} · {schema?.row_count?.toLocaleString()} rows
          </p>
        </div>
      </div>

      <div style={{ display:'grid', gridTemplateColumns:'1fr 280px', gap:'1.5rem', alignItems:'start' }}>

        {/* Left — content selector */}
        <div>
          <div style={{ background:'#fff', border:'1px solid #E2EEF9', borderRadius:'12px', padding:'1.25rem', marginBottom:'1rem' }}>
            <div style={{ display:'flex', justifyContent:'space-between', alignItems:'center', marginBottom:'1rem' }}>
              <h2 style={{ fontSize:'15px', fontWeight:'600', color:'#1A1A2E' }}>
                Select insights to include
              </h2>
              <div style={{ display:'flex', gap:'8px' }}>
                <button onClick={selectAll} style={styles.textBtn}>Select all</button>
                <button onClick={clearAll}  style={styles.textBtn}>Clear</button>
              </div>
            </div>

            {insights.length === 0 ? (
              <p style={{ fontSize:'13px', color:'#6B8BAA', textAlign:'center', padding:'2rem' }}>
                No insights found. Go back and generate some first.
              </p>
            ) : (
              <div style={{ display:'flex', flexDirection:'column', gap:'8px' }}>
                {insights.map(insight => (
                  <div
                    key={insight.id}


onClick={() => toggleSelect(insight.id || insight.title)}
style={{ display:'flex', alignItems:'center', gap:'12px', padding:'10px 12px', border: selected.includes(insight.id || insight.title) ? '2px solid #5BAADC' : '1px solid #E2EEF9', borderRadius:'10px', cursor:'pointer', background: selected.includes(insight.id || insight.title) ? '#F7FBFF' : '#fff' }}
>

                    <div style={{ width:'18px', height:'18px', borderRadius:'4px', border: selected.includes(insight.id || insight.title) ? '2px solid #5BAADC' : '2px solid #E2EEF9', background: selected.includes(insight.id || insight.title) ? '#5BAADC' : '#fff', display:'flex', alignItems:'center', justifyContent:'center', flexShrink:0 }}>
  {selected.includes(insight.id || insight.title) && (
    <span style={{ color:'#fff', fontSize:'12px', lineHeight:1 }}>✓</span>
  )}
</div>



                    <div style={{ flex:1 }}>
                      <div style={{ fontSize:'13px', fontWeight:'500', color:'#1A1A2E' }}>
                        {insight.title}
                      </div>
                      <div style={{ fontSize:'11px', color:'#6B8BAA', marginTop:'2px' }}>
                        {new Date(insight.created_at).toLocaleDateString()}
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>

        {/* Right — format + export */}
        <div style={{ display:'flex', flexDirection:'column', gap:'1rem' }}>

          {/* Format picker */}
          <div style={{ background:'#fff', border:'1px solid #E2EEF9', borderRadius:'12px', padding:'1.25rem' }}>
            <h2 style={{ fontSize:'15px', fontWeight:'600', color:'#1A1A2E', marginBottom:'12px' }}>
              Export format
            </h2>
            <div style={{ display:'flex', flexDirection:'column', gap:'8px' }}>
              {[
                { id:'pdf', label:'PDF Report', desc:'Print-ready document', icon:'📄' },


                { id:'csv',   label:'CSV Data',    desc:'Raw data export',      icon:'📊' },
                { id:'share', label:'Share link',  desc:'Send to anyone',       icon:'🔗' },


              ].map(f => (
                <div
                  key={f.id}
                  onClick={() => setFormat(f.id)}
                  style={{ display:'flex', alignItems:'center', gap:'10px', padding:'10px 12px', border: format === f.id ? '2px solid #5BAADC' : '1px solid #E2EEF9', borderRadius:'10px', cursor:'pointer', background: format === f.id ? '#F7FBFF' : '#fff' }}
                >
                  <span style={{ fontSize:'20px' }}>{f.icon}</span>
                  <div>
                    <div style={{ fontSize:'13px', fontWeight:'500', color:'#1A1A2E' }}>{f.label}</div>
                    <div style={{ fontSize:'11px', color:'#6B8BAA' }}>{f.desc}</div>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Summary */}
          <div style={{ background:'#E2EEF9', borderRadius:'12px', padding:'1rem' }}>
            <div style={{ fontSize:'12px', color:'#6B8BAA', marginBottom:'4px' }}>Selected</div>
            <div style={{ fontSize:'22px', fontWeight:'700', color:'#1A1A2E' }}>
              {selected.length} insight{selected.length !== 1 ? 's' : ''}
            </div>
          </div>

          {/* Export button */}
          <button


            onClick={format === 'pdf' ? handleExportPDF : format === 'csv' ? handleExportCSV : handleShare}

            
            disabled={exporting || selected.length === 0}
            style={{ padding:'12px', background: selected.length === 0 ? '#E2EEF9' : '#5BAADC', color: selected.length === 0 ? '#6B8BAA' : '#fff', border:'none', borderRadius:'10px', fontSize:'14px', fontWeight:'600', cursor: selected.length === 0 ? 'not-allowed' : 'pointer' }}
          >
            {exporting ? 'Exporting...' : `Download ${format.toUpperCase()}`}
          </button>

          {selected.length === 0 && (
            <p style={{ fontSize:'12px', color:'#C4661A', textAlign:'center' }}>
              Select at least one insight to export
            </p>
          )}
        </div>
      </div>
    </Layout>
  )
}

const styles = {
  textBtn: {
    background:   'transparent',
    border:       '1px solid #E2EEF9',
    borderRadius: '6px',
    padding:      '4px 10px',
    fontSize:     '12px',
    color:        '#6B8BAA',
    cursor:       'pointer',
  },
}